file_extension "ccdata";

table someTable2 
{
    unk0: string;
}

table Entry 
{
    name: string;
    is_root: bool;
    model_file: string;
    material_file: string;
    anim_file: string;
    unk3: string;
    anim_file_list: [string];
    unk4: bool;
    shared_file_list: [string];
    unk5: [string];
}

table Entry2 
{
    name: string;
    entries: [Entry3];
}

table Entry3 
{
    name: string;
	type: string;
    unk0: [Entry4];
}
table Entry4 
{
    type: string;
	enable: uint;
}

table CharacterCreationData 
{
    entries: [Entry];
    unk1: someTable2;
    unk2: uint;
    unk3: [Entry2];
}

root_type CharacterCreationData;
