namespace Titan.Animation;

table IntParam 
{
    name: string;
    min: uint32;
    max: uint32;
    default_val: uint32;
}

table FloatParam 
{
    name: string;
    min: float;
    max: float;
    default_val: float;
}

table BoolParam 
{
    name: string;
    val: bool;
}

table Trigger 
{
    name: string;
}

table Entry
{
    int_params: [IntParam];
    float_params: [FloatParam];
    bool_params: [BoolParam];
    triggers: [Trigger];
}

table TRACP 
{
    table: Entry;
}

root_type TRACP;