include "common.fbs";

namespace Titan.Model;

file_extension "trmtr";

enum UVWrapMode: uint32 {
    CLAMP = 0,
    WRAP = 1,
    MIRROR_CLAMP = 2,
    MIRROR_CLAMP_TO_EDGE = 3,
    MIRROR_CLAMP_TO_BORDER = 4,
    CLAMP_TO_BORDER = 5,
    MIRROR = 6,
    CLAMP_TO_EDGE = 7,
}

table SamplerState {
    sampler_state_0: uint32 = 0x0;
    sampler_state_1: uint32 = 0x0;
    sampler_state_2: uint32 = 0x0;
    sampler_state_3: uint32 = 0x0;
    sampler_state_4: float;
    sampler_state_5: float;
    sampler_state_6: float;
    sampler_state_7: float;
    sampler_state_8: float;
    repeat_u: UVWrapMode = CLAMP;
    repeat_v: UVWrapMode = CLAMP;
    repeat_w: UVWrapMode = CLAMP; //Never used
    border_color: Titan.Math.RGBA;
}

table Float4Parameter {
    color_name: string;
    color_value: Titan.Math.RGBA; 
}

table FloatParameter {
    float_name: string;
    float_value: float;
}

table IntParameter {
    int_name: string;
    int_value: int32 = -1;
}

table StringParameter {
    string_name: string;
    string_value: string;
}

table Shader {
    shader_name: string;
    shader_values: [StringParameter];
}

table Texture  {
    texture_name: string;
    texture_file: string;
    texture_slot: uint32 = 0; // Sampler ID; retained name for API compatibility.
}

table Byte_Extra {
    //Only pm0448 has it as 0x0 in Transparent Shader
    value: int8 = -1; 
}

table Int_Extra {
    res_0: uint32;
    //0 when Transparent
    //1 when NonDirectional
    value: int32 = -1;
}

table Material{
    name: string; 
    shaders: [Shader]; 
    textures: [Texture];
    samplers: [SamplerState]; 
    float_parameter: [FloatParameter];
    unk_5: string; //Always empty
    float4_light_parameter: [Float4Parameter];
    float4_parameter: [Float4Parameter];
    unk_8: string; //Always empty
    int_parameter: [IntParameter];
    unk_10: string; //Always empty
    unk_11: string; //Always empty
    unk_12: string; //Always empty
    byte_extra: Byte_Extra;
    int_extra: Int_Extra;
    alpha_type: string;
}

table TRMTR{
    res_0: uint32;
    materials: [Material];
}

root_type TRMTR;