include "../common.fbs";

namespace Titan.TrinityScene;

union PropVal
{
    PropInt,
    PropDec,
    PropStr,
    PropEnum,
    PropList,
    PropTable,
    PropUnion,
    Titan.Math.Vec2,
    Titan.Math.Vec3,
    Titan.Math.Vec4,
}

table PropInt
{
    data: ulong;
    size: ubyte;
}

table PropDec
{
    data: double;
    size: ubyte;
}

table PropStr
{
    data: string;
}

table PropEnum
{
    name: string;
    val: int;
}

table PropUnion
{
    type: PropEnum;
    val: PropTable;
}

table PropField
{
    name: string;
    value: PropVal;
}

table PropTable
{
    fields: [PropField];
}

table PropList
{
    vals: [PropVal];
}

table TrinityPropertySheet
{
    property_name: string;
    property_template: string;
    unk0: [PropTable];
}

root_type TrinityPropertySheet;
